### ISSUE TITLE
Missing required files causes File Not Found error

### ISSUE THREAD

**Issue by mariobadr** [MarkUsProject/markus-moss#11]
When performing a `'download_submission_files'` action with the default file glob, students who are missing a required file cause a file not found error:

```
Traceback (most recent call last):
  File "/home/mbadr/.pyenv/versions/3.9.6/bin/markusmoss", line 33, in <module>
    sys.exit(load_entry_point('markusmoss==0.0.1', 'console_scripts', 'markusmoss')())
  File "/home/mbadr/.pyenv/versions/3.9.6/lib/python3.9/site-packages/markusmoss/cli.py", line 62, in cli
    MarkusMoss(**kwargs).run(actions=actions)
  File "/home/mbadr/.pyenv/versions/3.9.6/lib/python3.9/site-packages/markusmoss/markusmoss.py", line 77, in run
    getattr(self, action)()
  File "/home/mbadr/.pyenv/versions/3.9.6/lib/python3.9/site-packages/markusmoss/markusmoss.py", line 121, in run_moss
    self.moss.addFile(filename, os.path.relpath(filename, self.workdir))
  File "/home/mbadr/.pyenv/versions/3.9.6/lib/python3.9/site-packages/mosspy/moss.py", line 82, in addFile
    raise Exception("addFile({}) => File Not Found".format(file_path))
Exception: addFile(/home/mbadr/anita/110-21f/academic-offences/a1/moss/submission_files/STUDENT/a1.pdf) => File Not Found
```

My configurations (not including priate ones) are:

```
language="python"
markus_assignment='A1'
actions=['download_submission_files','download_starter_files','run_moss','download_moss_report']
```

The desired behaviour, in my opinion, would be to simply download all the files that were submitted, regardless of requirements.

**Comment by mariobadr** [comment]
Sorry, I had the action wrong. This occurs for the `'run_moss'` action. I am not sure what the desired behaviour here would be, but ideally not an error?
